- name: Add bash prompt to ~/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: ". {{ role_path }}/files/prompt.sh"
    insertbefore: '^unset color_prompt force_color_prompt'

- name: Add bash prompt to ~/.bashrc (root)
  become: true
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    line: ". {{ role_path }}/files/prompt.sh"
    insertbefore: '^unset color_prompt force_color_prompt'

- name: Add recursive sudo aliases
  become: true
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    block: |
      # Enable recursive sudo aliases
      alias sudo="sudo "
