# Allow `C-b b` to go to the last window (like with screen)
bind-key -T prefix b last-window

# Enter copy-mode with `C-b Esc` (like with screen)
bind-key -T prefix Escape copy-mode

# Swap window with `C-b S`
bind-key -T prefix S command-prompt -T window-target { swap-window -d -t "%%" }

# Allow scroll up/down with mouse
#set -g mouse on

# Set history buffer
set -g history-limit 100000

# Copy buffer to OS clipboard
set -s copy-command 'xsel --input --clipboard'

# Fix prompt colors
set -g default-terminal "screen-256color"
