- name: Configuring Ubuntu 26.04
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: packages
      tags: packages

    - name: Configure keyboard
      ansible.builtin.import_role:
        name: keyboard
      vars:
        keyboard_delay: "250"
        keyboard_rate: "20"
        keyboard_input_sources: "[('xkb', 'fr'), ('ibus', 'Unikey')]"
      tags: keyboard

    - name: Configure keyboard shortcuts
      ansible.builtin.import_role:
        name: keyboard_shortcuts
      vars:
        keyboard_shortcuts_maximize_vertically: "['<Alt>F11']"
        keyboard_shortcuts_maximize_horizontally: "['<Alt>F12']"
      tags: keyboard-shortcuts

    - name: Configure touchpad
      ansible.builtin.include_role:
        name: touchpad
        apply:
          tags:
            - touchpad
      vars:
        touchpad_tap_to_click: "false"
        touchpad_click_method: "'fingers'"
        touchpad_edge_scrolling_enabled: "false"
        touchpad_two_finger_scrolling_enabled: "true"
        touchpad_natural_scroll: "false"
      when: has_touchpad | bool
      tags: touchpad

    - name: Configure desktop
      ansible.builtin.import_role:
        name: desktop
      tags: desktop

    - name: Install fonts
      ansible.builtin.import_role:
        name: fonts
      tags: fonts

    # - ansible.builtin.import_role:
    #     name: gnome_extensions
    #   vars:
    #     gnome_extensions:
    #       - id: 36 # https://extensions.gnome.org/extension/36/lock-keys/
    #         enable: yes
    #       - id: 3010 # https://extensions.gnome.org/extension/3010/system-monitor-next/
    #         enable: yes
    #       - id: 4709 # https://extensions.gnome.org/extension/4709/another-window-session-manager/
    #         enable: yes
    #       - id: 3843 # https://extensions.gnome.org/extension/3843/just-perfection/
    #         enable: yes
    #   tags: gnome-extensions

    - name: Configure Ptyxis terminal
      ansible.builtin.import_role:
        name: terminal
      vars:
        terminal_scrollback_lines: "100000"
        terminal_background_opacity: "0.85"
      tags: terminal

    - name: Configure bash
      ansible.builtin.import_role:
        name: bash
      tags: bash

    - name: Configure zsh
      ansible.builtin.import_role:
        name: zsh
      tags: zsh

    - name: Configure dot files
      ansible.builtin.import_role:
        name: dotfiles
      tags: dotfiles

    # - ansible.builtin.import_role:
    #     name: kubectl
    #   tags: kubectl
