# noqa: package-latest
- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - bash-completion
      - curl
      - dconf-editor
      - flatpak
      - gimp
      - git
      - gnome-shell-extension-manager
      - gnome-software-plugin-flatpak
      - gnome-tweaks
      - gnome-weather
      - gparted
      - htop
      - imagemagick-7.q16
      - mkvtoolnix-gui
      - neovim
      - pdfarranger
      - ripgrep
      - seahorse
      - sqlite3
      - sysstat
      - tig
      - tmux
      - trash-cli
      - tree
      - vim-gtk3
      - wget
      - xsel
      - zsh
    state: latest

- name: Add the Flathub Flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak packages
  community.general.flatpak:
    name:
      - com.vysp3r.ProtonPlus
      - io.podman_desktop.PodmanDesktop
      - org.videolan.VLC
    state: latest

- name: Install Snap packages
  become: true
  community.general.snap:
    name:
      - discord
      - libreoffice
      - slack

# AWS CLI

- name: Install AWS CLI snap package
  become: true
  community.general.snap:
    name: aws-cli
    classic: true

# gcloud CLI

- name: Import gcloud-cli tasks
  ansible.builtin.import_tasks: gcloud-cli.yml

# GitHub CLI

- name: Import gh-cli tasks
  ansible.builtin.import_tasks: gh-cli.yml
