- name: "Symlink dot files"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ role_path }}/files/dotfiles/.*"

# direnv

- name: 'Create the directory "{{ lookup("env", "HOME") }}/.config/direnv"' # noqa: name[template]
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/direnv"
    state: directory
    mode: '755'

- name: 'Create the symlink "{{ lookup("env", "HOME") }}/.config/direnv/direnvrc"' # noqa: name[template]
  ansible.builtin.file:
    src: "{{ role_path }}/files/direnv/direnvrc"
    dest: "{{ lookup('env', 'HOME') }}/.config/direnv/direnvrc"
    state: link

# htop

- name: 'Create the directory "{{ lookup("env", "HOME") }}/.config/htop"' # noqa: name[template]
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/htop"
    state: directory
    mode: '755'

- name: 'Copy the file "{{ lookup("env", "HOME") }}/.config/htop/htoprc"' # noqa: name[template]
  ansible.builtin.copy:
    src: htop/htoprc
    dest: "{{ lookup('env', 'HOME') }}/.config/htop/htoprc"
    mode: '644'
