# noqa: package-latest
- name: Install cosign
  become: true
  ansible.builtin.apt:
    name: cosign
    state: latest

- name: Install tenv
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    LATEST_VERSION=$(curl --silent https://api.github.com/repos/tofuutils/tenv/releases/latest | jq -r .tag_name)
    curl -o "/tmp/tenv_${LATEST_VERSION}_amd64.deb" -L "https://github.com/tofuutils/tenv/releases/latest/download/tenv_${LATEST_VERSION}_amd64.deb"
    sudo dpkg -i "/tmp/tenv_${LATEST_VERSION}_amd64.deb"
    rm "/tmp/tenv_${LATEST_VERSION}_amd64.deb"
  changed_when: false

- name: Generate tenv completions
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    tenv completion bash > /etc/bash_completion.d/tenv
    tenv completion zsh > /usr/share/zsh/site-functions/_tenv
  changed_when: false
