# GRUB

- name: Set GRUB timeout to 5
  become: true
  ansible.builtin.copy:
    src: grub.d/timeout.cfg
    dest: /etc/default/grub.d/timeout.cfg
    mode: '644'
  notify: Update GRUB

# Suspend: keyboard & mouse must not wake up

- name: Copy file /etc/rc.local
  become: true
  ansible.builtin.copy:
    src: rc.local
    dest: /etc/rc.local
    mode: '755'

# APT

- name: Copy the file /etc/apt/apt.conf.d/99-no-pager.conf
  become: true
  ansible.builtin.copy:
    src: apt.conf.d/99-no-pager.conf
    dest: /etc/apt/apt.conf.d/99-no-pager.conf
    mode: '644'

# sysctl

- name: Create sysctl file /etc/sysctl.d/99-swappiness.conf
  become: true
  ansible.builtin.template:
    src: sysctl.d/99-swappiness.conf.j2
    dest: /etc/sysctl.d/99-swappiness.conf
    mode: '644'
  notify: Reload sysctl

# /etc/hosts

- name: Add hosts in /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.1.10 brother
      192.168.1.11 rpi3bplus
      192.168.1.12 a5

# Disable password prompts for some commands
- name: Copy file /etc/polkit-1/rules.d/disable-passwords.rules
  become: true
  ansible.builtin.copy:
    src: polkit-1/rules.d/disable-passwords.rules
    dest: /etc/polkit-1/rules.d/disable-passwords.rules
    mode: '644'
