# APT

- name: Copy the file /etc/apt/apt.conf.d/99-no-pager.conf
  become: true
  ansible.builtin.copy:
    src: apt.conf.d/99-no-pager.conf
    dest: /etc/apt/apt.conf.d/99-no-pager.conf
    mode: '644'

# sysctl

- name: Create sysctl file /etc/sysctl.d/99-swappiness.conf
  become: true
  ansible.builtin.template:
    src: sysctl.d/99-swappiness.conf.j2
    dest: /etc/sysctl.d/99-swappiness.conf
    mode: '644'
  notify: Reload sysctl
