- name: Run Homebrew installation command
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
