# Keyboard

- name: 'Set "Switch input source" keyboard shortcut to "{{ keyboard_shortcuts_switch_input_source }}"'
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-input-source
    value: "{{ keyboard_shortcuts_switch_input_source }}"

- name: 'Set "Switch input source backward" keyboard shortcut to "{{ keyboard_shortcuts_switch_input_source_backward }}"'
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-input-source-backward
    value: "{{ keyboard_shortcuts_switch_input_source_backward }}"

# Window

- name: 'Set "Maximize window vertically" keyboard shortcut to "{{ keyboard_shortcuts_maximize_vertically }}"'
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/maximize-vertically
    value: "{{ keyboard_shortcuts_maximize_vertically }}"

- name: 'Set "Maximize window horizontally" keyboard shortcut to "{{ keyboard_shortcuts_maximize_horizontally }}"'
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/maximize-horizontally
    value: "{{ keyboard_shortcuts_maximize_horizontally }}"

- name: Unset "Switch to workspace above" keyboard shortcut
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
    value: "@as []"

- name: Unset "Switch to workspace below" keyboard shortcut
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
    value: "@as []"

- name: Set "Switch to workspace left" keyboard shortcut
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-left
    value: "['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left']"

- name: Set "Switch to workspace right" keyboard shortcut
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-right
    value: "['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right']"
