- name: Read the default profile UUID
  community.general.dconf:
    key: "/org/gnome/Ptyxis/default-profile-uuid"
    state: read
  register: terminal_default_profile

- name: Set 'terminal_default_profile_uuid' variable
  ansible.builtin.set_fact:
    terminal_default_profile_uuid: >-
      {{ terminal_default_profile.value | ansible.builtin.regex_replace("^'?(\w+)'?$", "\1") }}

- name: Do not use system font
  community.general.dconf:
    key: "/org/gnome/Ptyxis/use-system-font"
    value: "false"

- name: 'Set font name to "{{ terminal_font_name }}"'
  community.general.dconf:
    key: "/org/gnome/Ptyxis/font-name"
    value: "{{ terminal_font_name }}"

- name: 'Set "User bright colors for bold" to "{{ terminal_bold_is_bright }}"'
  community.general.dconf:
    key: "/org/gnome/Ptyxis/Profiles/{{ terminal_default_profile_uuid }}/bold-is-bright"
    value: "{{ terminal_bold_is_bright }}"

- name: 'Set scrollback lines to "{{ terminal_scrollback_lines }}"'
  community.general.dconf:
    key: "/org/gnome/Ptyxis/Profiles/{{ terminal_default_profile_uuid }}/scrollback-lines"
    value: "{{ terminal_scrollback_lines }}"

- name: 'Set background opacity to "{{ terminal_background_opacity }}"'
  community.general.dconf:
    key: "/org/gnome/Ptyxis/Profiles/{{ terminal_default_profile_uuid }}/opacity"
    value: "{{ terminal_background_opacity }}"
